"""Prosthetic inactive state

Revision ID: 1c16ed91c7df
Revises: 5a4e465393e1
Create Date: 2025-03-31 02:53:38.183165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c16ed91c7df"
down_revision: Union[str, None] = "5a4e465393e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the is_active column with a default value of True and set it for existing rows
    op.add_column(
        "prosthetic",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),  # Sets the default for new rows going forward
        ),
    )
    # Ensure all existing rows have is_active set to True
    op.execute("UPDATE prosthetic SET is_active = TRUE WHERE is_active IS NULL")

    op.add_column(
        "prosthetic", sa.Column("deactivation_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "prosthetic", sa.Column("deactivation_year", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "prosthetic",
        "user_adaptation",
        existing_type=postgresql.ENUM(
            "Poor", "Moderate", "Good", "Excellent", "Unknown", name="useradaptation"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "prosthetic",
        "user_adaptation",
        existing_type=postgresql.ENUM(
            "Poor", "Moderate", "Good", "Excellent", "Unknown", name="useradaptation"
        ),
        nullable=False,
    )
    op.drop_column("prosthetic", "deactivation_year")
    op.drop_column("prosthetic", "deactivation_date")
    op.drop_column("prosthetic", "is_active")
    # ### end Alembic commands ###
