"""init

Revision ID: 5a4e465393e1
Revises:
Create Date: 2025-03-27 02:35:50.742655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5a4e465393e1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("ssn", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column(
            "phone_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column(
            "sex", sa.Enum("Male", "Female", "Unknown", name="sex"), nullable=False
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column(
            "limb_dominance",
            sa.Enum("Left", "Right", "Ambidextrous", "Unknown", name="limbdominance"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
        sa.UniqueConstraint("ssn"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "sex", sa.Enum("Male", "Female", "Unknown", name="sex"), nullable=False
        ),
        sa.Column("birth_date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "patient_injury",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("injury_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("injury_date", sa.Date(), nullable=True),
        sa.Column("injury_year", sa.Integer(), nullable=True),
        sa.Column("treated", sa.Boolean(), nullable=True),
        sa.Column(
            "treatment_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("current_impact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "side",
            sa.Enum("Left", "Right", "Bilateral", "Unknown", name="side"),
            nullable=False,
        ),
        sa.Column("details", sa.TEXT(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_injury_id"), "patient_injury", ["id"], unique=False
    )
    op.create_table(
        "patient_medical_condition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "medical_condition_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("diagnosis_date", sa.Date(), nullable=True),
        sa.Column("diagnosis_year", sa.Integer(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum("Mild", "Moderate", "Severe", "Unknown", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "treatment_status",
            sa.Enum(
                "Ongoing",
                "UnderControl",
                "Recovered",
                "Untreated",
                "Unknown",
                name="treatmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("details", sa.TEXT(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_patient_medical_condition_id"),
        "patient_medical_condition",
        ["id"],
        unique=False,
    )
    op.create_table(
        "prosthetic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column("installation_year", sa.Integer(), nullable=True),
        sa.Column("usage_duration", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "Transtibial",
                "Transfemoral",
                "PartialFoot",
                "Syme",
                "KneeDisarticulation",
                "HipDisarticulation",
                "Transhumeral",
                "Transradial",
                "Hand",
                "ShoulderDisarticulation",
                "Finger",
                "Toe",
                "Other",
                name="prosthetictype",
            ),
            nullable=False,
        ),
        sa.Column(
            "other_type", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "side",
            sa.Enum("Left", "Right", "Bilateral", "Unknown", name="side"),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column(
            "material",
            sa.Enum(
                "CarbonFiber",
                "Titanium",
                "PlasticComposite",
                "Aluminum",
                "Other",
                name="materialtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "other_material",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "manufacturer", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("residual_limb_length", sa.Float(), nullable=True),
        sa.Column(
            "alignment",
            sa.Enum("Static", "Dynamic", "Other", name="alignment"),
            nullable=True,
        ),
        sa.Column(
            "other_alignment",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "suspension_system",
            sa.Enum(
                "Suction",
                "VacuumAssisted",
                "PinLock",
                "Straps",
                "Other",
                name="suspensionsystem",
            ),
            nullable=True,
        ),
        sa.Column(
            "other_suspension_system",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "socket_fit",
            sa.Enum(
                "Perfect",
                "SlightDiscomfort",
                "Loose",
                "Painful",
                "Unknown",
                name="socketfit",
            ),
            nullable=True,
        ),
        sa.Column(
            "foot_type",
            sa.Enum(
                "SACH",
                "DynamicResponse",
                "Multiaxial",
                "EnergyStoring",
                "Microprocessor",
                "Other",
                name="foottype",
            ),
            nullable=True,
        ),
        sa.Column(
            "other_foot_type",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "knee_type",
            sa.Enum(
                "Mechanical",
                "Hydraulic",
                "Pneumatic",
                "MicroprocessorControlled",
                "Other",
                name="kneetype",
            ),
            nullable=True,
        ),
        sa.Column(
            "other_knee_type",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "pelvic_socket",
            sa.Enum(
                "Rigid",
                "Flexible",
                "Adjustable",
                "VacuumAssisted",
                "Other",
                name="pelvicsocket",
            ),
            nullable=True,
        ),
        sa.Column(
            "other_pelvic_socket",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "finger_position",
            sa.Enum("Thumb", "Index", "Middle", "Ring", "Pinky", name="fingerposition"),
            nullable=True,
        ),
        sa.Column(
            "toe_position",
            sa.Enum(
                "BigToe",
                "SecondToe",
                "MiddleToe",
                "FourthToe",
                "LittleToe",
                name="toeposition",
            ),
            nullable=True,
        ),
        sa.Column(
            "control_system",
            sa.Enum(
                "Mechanical",
                "Hybrid",
                "MicroprocessorControlled",
                "Other",
                name="controlsystem",
            ),
            nullable=True,
        ),
        sa.Column(
            "other_control_system",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("grip_strength", sa.Float(), nullable=True),
        sa.Column("range_of_motion_min", sa.Float(), nullable=True),
        sa.Column("range_of_motion_max", sa.Float(), nullable=True),
        sa.Column("stiffness", sa.Float(), nullable=True),
        sa.Column("shock_absorption_energy", sa.Float(), nullable=True),
        sa.Column(
            "activity_level",
            sa.Enum(
                "Low", "Moderate", "High", "Athletic", "Other", name="activitylevel"
            ),
            nullable=True,
        ),
        sa.Column(
            "other_activity_level",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "user_adaptation",
            sa.Enum(
                "Poor",
                "Moderate",
                "Good",
                "Excellent",
                "Unknown",
                name="useradaptation",
            ),
            nullable=False,
        ),
        sa.Column("details", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prosthetic_id"), "prosthetic", ["id"], unique=False)
    op.create_index(
        op.f("ix_prosthetic_installation_date"),
        "prosthetic",
        ["installation_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prosthetic_installation_date"), table_name="prosthetic")
    op.drop_index(op.f("ix_prosthetic_id"), table_name="prosthetic")
    op.drop_table("prosthetic")
    op.drop_index(
        op.f("ix_patient_medical_condition_id"), table_name="patient_medical_condition"
    )
    op.drop_table("patient_medical_condition")
    op.drop_index(op.f("ix_patient_injury_id"), table_name="patient_injury")
    op.drop_table("patient_injury")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("patient")
    # ### end Alembic commands ###
