"""add_session_model

Revision ID: fe2263b33be8
Revises: 1d8bbc347233
Create Date: 2025-04-24 21:11:58.542340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe2263b33be8'
down_revision: Union[str, None] = '1d8bbc347233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gait_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('annotated_video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('ai_analysis', sa.TEXT(), nullable=True),
    sa.Column('recommendations', sa.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('analysis_status', sa.Enum('Initial', 'Pending', 'InProgress', 'Completed', 'Error', name='analysisstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gait_session_id'), 'gait_session', ['id'], unique=False)
    op.create_index(op.f('ix_gait_session_patient_id'), 'gait_session', ['patient_id'], unique=False)
    op.create_table('gait_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gait_session_id', sa.Integer(), nullable=False),
    sa.Column('measurement_index', sa.Integer(), nullable=False),
    sa.Column('stance_time_left', sa.Float(), nullable=True),
    sa.Column('stance_time_right', sa.Float(), nullable=True),
    sa.Column('swing_time_left', sa.Float(), nullable=True),
    sa.Column('swing_time_right', sa.Float(), nullable=True),
    sa.Column('step_time_left', sa.Float(), nullable=True),
    sa.Column('step_time_right', sa.Float(), nullable=True),
    sa.Column('double_support_time_left', sa.Float(), nullable=True),
    sa.Column('double_support_time_right', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gait_session_id'], ['gait_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gait_metrics_gait_session_id'), 'gait_metrics', ['gait_session_id'], unique=False)
    op.create_index(op.f('ix_gait_metrics_id'), 'gait_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_gait_metrics_measurement_index'), 'gait_metrics', ['measurement_index'], unique=False)
    op.create_table('gait_plot_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gait_session_id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('dist_left_filtered', sa.Float(), nullable=True),
    sa.Column('dist_right_filtered', sa.Float(), nullable=True),
    sa.Column('is_peak_left', sa.Boolean(), nullable=False),
    sa.Column('is_peak_right', sa.Boolean(), nullable=False),
    sa.Column('is_minima_left', sa.Boolean(), nullable=False),
    sa.Column('is_minima_right', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gait_session_id'], ['gait_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gait_plot_data_frame_number'), 'gait_plot_data', ['frame_number'], unique=False)
    op.create_index(op.f('ix_gait_plot_data_gait_session_id'), 'gait_plot_data', ['gait_session_id'], unique=False)
    op.create_index(op.f('ix_gait_plot_data_id'), 'gait_plot_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gait_plot_data_id'), table_name='gait_plot_data')
    op.drop_index(op.f('ix_gait_plot_data_gait_session_id'), table_name='gait_plot_data')
    op.drop_index(op.f('ix_gait_plot_data_frame_number'), table_name='gait_plot_data')
    op.drop_table('gait_plot_data')
    op.drop_index(op.f('ix_gait_metrics_measurement_index'), table_name='gait_metrics')
    op.drop_index(op.f('ix_gait_metrics_id'), table_name='gait_metrics')
    op.drop_index(op.f('ix_gait_metrics_gait_session_id'), table_name='gait_metrics')
    op.drop_table('gait_metrics')
    op.drop_index(op.f('ix_gait_session_patient_id'), table_name='gait_session')
    op.drop_index(op.f('ix_gait_session_id'), table_name='gait_session')
    op.drop_table('gait_session')
    # ### end Alembic commands ###