import {
  LimbDominance,
  limbDominanceIcons,
  limbDominanceLabels,
  type Patient,
  type PatientListItem,
  Sex,
  sexIcons,
  sexLabels,
} from './patient.type';
import { type Injury, Side, sideLabels } from './injury.type';
import {
  type MedicalCondition,
  Severity,
  severityLabels,
  TreatmentStatus,
  treatmentStatusLabels,
} from './medical-condition.type';
import {
  ActivityLevel,
  activityLevelLabels,
  Alignment,
  alignmentLabels,
  ControlSystem,
  controlSystemLabels,
  FingerPosition,
  fingerPositionLabels,
  FootType,
  footTypeLabels,
  KneeType,
  kneeTypeLabels,
  MaterialType,
  materialTypeLabels,
  PelvicSocket,
  pelvicSocketLabels,
  type Prosthetic,
  ProstheticType,
  prostheticTypeLabels,
  SocketFit,
  socketFitLabels,
  SuspensionSystem,
  suspensionSystemLabels,
  ToePosition,
  toePositionLabels,
  UserAdaptation,
  userAdaptationLabels,
} from './prosthetic.type';
import {
  AnalysisStatus,
  analysisStatusColors,
  analysisStatusLabels,
  type GaitSession,
  type GaitSessionListItem,
} from './session.type';

export type PaginatedResponse<T> = {
  items: T[];
  page: number;
  count: number;
  totalPages: number;
  hasNextPage: boolean;
};

export {
  Patient,
  PatientListItem,
  LimbDominance,
  limbDominanceLabels,
  limbDominanceIcons,
  Sex,
  sexLabels,
  sexIcons,
  Injury,
  Side,
  sideLabels,
  MedicalCondition,
  Severity,
  severityLabels,
  TreatmentStatus,
  treatmentStatusLabels,
  Prosthetic,
  ProstheticType,
  prostheticTypeLabels,
  ActivityLevel,
  activityLevelLabels,
  Alignment,
  alignmentLabels,
  ControlSystem,
  controlSystemLabels,
  FingerPosition,
  fingerPositionLabels,
  FootType,
  footTypeLabels,
  KneeType,
  kneeTypeLabels,
  MaterialType,
  materialTypeLabels,
  PelvicSocket,
  pelvicSocketLabels,
  SocketFit,
  socketFitLabels,
  SuspensionSystem,
  suspensionSystemLabels,
  ToePosition,
  toePositionLabels,
  UserAdaptation,
  userAdaptationLabels,
  GaitSession,
  GaitSessionListItem,
  AnalysisStatus,
  analysisStatusLabels,
  analysisStatusColors,
};
